[package]
name = "f256"
version = "0.11.2"
edition = "2021"
rust-version = "1.86.0"
description = "Octuple-precision floating-point arithmetic."
documentation = "https://docs.rs/f256/"
readme = "README.md"
homepage = "https://github.com/mamrhein/f256.rs"
repository = "https://github.com/mamrhein/f256.rs"
license-file = "LICENSE.TXT"
keywords = ["arithmetics", "floating-point", "number", "precision"]
categories = ["data-structures", "mathematics"]
exclude = ["analysis/*", "tests/*"]

[workspace]
members = [".", "pow2_div_pow5_lut", "pow2_div_pow10_lut", "pow5_div_pow2_lut", "pow10_div_pow2_lut"]
exclude = ["analysis/bkm_flop_lut", "analysis/compute_required_bits", "analysis/payne_hanek"]

[dependencies]
f256_pow2_div_pow5_lut = { path = "pow2_div_pow5_lut", version = "0.1" }
f256_pow2_div_pow10_lut = { path = "pow2_div_pow10_lut", version = "0.2" }
f256_pow5_div_pow2_lut = { path = "pow5_div_pow2_lut", version = "0.1" }
f256_pow10_div_pow2_lut = { path = "pow10_div_pow2_lut", version = "0.1" }
libm = "0.2"
num-traits = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
csv = "1"
serde = { version = "1", features = ["derive"] }

[features]
default = ["std"]
std = ["num-traits/std"]
